version: "3"

services:

  db:
    image: postgres
    container_name: db
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST='db'
      - POSTGRES_PORT=$5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
    - db-volume:/var/lib/postgresql/data
    #   - ./API/dbInit:/docker-entrypoint-initdb.d


  api:
    build: ./API
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-volume: